title: AStartup Toolkit
email: info@astartup.net
description: >- # this means to ignore newlines until "baseurl:"
  AStartup GitHub product documentation and business model canvas Jekyll 
  template for apps, game dev, books, hardware, and your product.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AStarStartup
github_username:  AStarStartup

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

defaults:
- scope:
    path: ""
  values:
    toc: true